[libraries]
moengageCore = { module = "com.moengage:moe-android-sdk", version = "12.9.02" }
segment = { module = "com.segment.analytics.android:analytics", version = "4.9.0" }
segmentKotlin = { module = "com.segment.analytics.kotlin:android", version = "1.5.0" }