[libraries]
moengageCore = { module = "com.moengage:moe-android-sdk", version = "14.00.00" }
segment = { module = "com.segment.analytics.android:analytics", version = "4.11.3" }
segmentKotlin = { module = "com.segment.analytics.kotlin:android", version = "1.19.0" }
material = { module = "com.google.android.material:material", version = "1.12.0" }

[plugins]
plugin-google-play-service = { id = "com.google.gms.google-services", version = "4.4.2" }