[libraries]
moengageCore = { module = "com.moengage:moe-android-sdk", version = "12.3.02" }
segment = { module = "com.segment.analytics.android:analytics", version = "4.9.0" }
# plugins
gradlePlugin-googleService = { module = "com.google.gms:google-services", version = "4.3.10" }

[bundles]
gradlePlugins = ["gradlePlugin-googleService"]