name: Update MoEngage Core Version

on:
  workflow_dispatch:
    inputs:
      moengage_version:
        description: 'The new moengageCore SDK version (e.g., 14.03.00)'
        required: true
      release_notes:
        description: 'The release notes (bullet points, multi-line)'
        required: true
        type: string

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyId }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}

jobs:
  update_moengage_core:
    environment: publishing_gradle_config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: source
          ref: "auto_update_moengage_core"
      - name: automation-repo-setup
        uses: ./source/.github/actions/common-repo-setup
        with:
          sdk_bot_access_token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Make scripts executable
        run: |
          chmod +x ./sdk-automation-scripts/scripts/android/shell/update_moengage_core_version.sh
      - name: Update moengageCore version
        run: ./sdk-automation-scripts/scripts/android/shell/update_moengage_core_version.sh "${{ github.event.inputs.moengage_version }}" "./source/gradle/libs.versions.toml"
      - name: Verify build
        run: |
          cd source
          ./gradlew assemble --stacktrace
      # - name: Update changelog file
      #   working-directory: source
      #   run: |
      #    kotlin ./scripts/update-changelog.main.kts "${{ github.event.inputs.release_notes }}" "${{ github.event.inputs.moengage_version }}"
      - name: Commit and push changes
        run: |
          cd source
          git add .
          git commit -m "chore: Update moengageCore version to ${{ github.event.inputs.moengage_version }}"
          git push origin auto_update_moengage_core